baseURL = 'https://gabriel.gizotti.com'
languageCode = 'en-us'
title = 'Gabriel Gizotti'
theme = 'hugo-coder'

[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "gizotti"

[markup.highlight]
style = "github-dark"

[params]
  author = "Gabriel Gizotti"
  info = "Software Engineer"
  description = "Gabriel Gizotti's personal website"
  keywords = "blog,developer,personal"
  # avatarurl = "images/avatar.jpg"
  gravatar = "gabriel@gizotti.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = true

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/gizotti/"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/gabriel-gizotti/"
# [[params.social]]
#   name = "Twitter"
#   icon = "fa-brands fa-x-twitter fa-2x"
#   weight = 3
#   url = "https://twitter.com/johndoe/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
  height = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'
